name: freechoice_music
description: A new bobosh project.
version: 0.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  audioplayers: ^4.1.0 #kald覺r覺labilir
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  flutter_native_splash:
  path_provider:
  card_swiper: ^3.0.1 #kald覺r覺labilir
  on_audio_query: ^2.9.0
  flutter_svg: ^2.0.5
#perfect_volume_control: ^1.0.5
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.5
  logger: ^1.1.0
  dio: ^5.3.3
  permission_handler: ^11.3.1
  animated_text_kit: ^4.2.2
  webview_flutter: ^4.4.1
  animations: ^2.0.10
  get_it:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Abril
      fonts:
        - asset: assets/fonts/abrilFatFace.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: YsabeauInfant
      fonts:
        - asset: assets/fonts/YsabeauInfant-r.ttf
        - asset: assets/fonts/YsabeauInfant-sbold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
